/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author HNDX
 */
public class explanation extends javax.swing.JFrame {

    /**
     * Creates new form explanation
     */
    public explanation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        jTextArea2.setBackground(new java.awt.Color(0, 204, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 102, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("   首都图书馆位于北京市朝阳区东三环，是北京市综合性大型公共图书馆。\n是原中华人民共和国文化部评定的\"国家一级图书馆\"，是首批\"全国古籍\n重点保护单位\"。\n\n   首都图书馆的历史可追溯至1913年，由鲁迅参与倡建的京师图书分馆、\n京师通俗图书馆和中央公园图书阅览三馆几经合并演变而成。北伐革命\n后，原三个图书馆几经更名、合并，改为北京市市立第一图书馆1953年\n，更名北京市图书馆，1956年10月，正式定名首都图书馆。\n\n   据2018年9月该图书馆官网信息显示，首都图书馆建筑面积3.7万平方米\n，设有20个阅览室，4000余个阅览座位，管藏文献逾845万册(件)，其\n中，古籍近50万册(件)，善本6000余部，闻名海内外的珍藏《车王府曲\n本》收各种戏曲、曲艺抄本1600余种，老唱片2万余张，收录了四大名\n旦唯一合唱的老唱片《四五花洞》。\n");
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea1.setBackground(new java.awt.Color(0, 204, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("   首都图书馆位于北京市朝阳区东三环，是北京市综合性大型公共图书馆。\n是原中华人民共和国文化部评定的\"国家一级图书馆\"，是首批\"全国古籍\n重点保护单位\"。\n\n   首都图书馆的历史可追溯至1913年，由鲁迅参与倡建的京师图书分馆、\n京师通俗图书馆和中央公园图书阅览三馆几经合并演变而成。北伐革命\n后，原三个图书馆几经更名、合并，改为北京市市立第一图书馆1953年\n，更名北京市图书馆，1956年10月，正式定名首都图书馆。\n\n   据2018年9月该图书馆官网信息显示，首都图书馆建筑面积3.7万平方米\n，设有20个阅览室，4000余个阅览座位，管藏文献逾845万册(件)，其\n中，古籍近50万册(件)，善本6000余部，闻名海内外的珍藏《车王府曲\n本》收各种戏曲、曲艺抄本1600余种，老唱片2万余张，收录了四大名\n旦唯一合唱的老唱片《四五花洞》。\n");
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("图书馆名称 ：  首都图书馆");

        jLabel8.setText("设计容量  ： 400万册 ");

        jLabel7.setText("地址      ： 北京市朝阳区");

        jLabel5.setText("建筑面积   ：   3.8万平方米  ");

        jLabel4.setText("建造单位   ：  北京市建筑设计研究院  ");

        jLabel2.setText(" 外文名称  ：   The capital library ");

        jLabel11.setText("藏书      ： 650万册(件)  ");

        jLabel3.setText("建馆日期   ：   2001年5月1日 ");

        jLabel9.setText("阅览室    ： 20个 ");

        jLabel10.setText("开馆时间  ： 周一至周日 9:00-19:30  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(67, 67, 67))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/t014e5b283ab5e6c436.jpg"))); // NOI18N

        jLabel12.setText("首都图书馆模型图");

        jTextArea3.setBackground(new java.awt.Color(0, 204, 51));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 102, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("   首都图书馆位于北京市朝阳区东三环，是北京市综合性大型公共图书馆。\n是原中华人民共和国文化部评定的\"国家一级图书馆\"，是首批\"全国古籍\n重点保护单位\"。\n\n   首都图书馆的历史可追溯至1913年，由鲁迅参与倡建的京师图书分馆、\n京师通俗图书馆和中央公园图书阅览三馆几经合并演变而成。北伐革命\n后，原三个图书馆几经更名、合并，改为北京市市立第一图书馆1953年\n，更名北京市图书馆，1956年10月，正式定名首都图书馆。\n\n   据2018年9月该图书馆官网信息显示，首都图书馆建筑面积3.7万平方米\n，设有20个阅览室，4000余个阅览座位，管藏文献逾845万册(件)，其\n中，古籍近50万册(件)，善本6000余部，闻名海内外的珍藏《车王府曲\n本》收各种戏曲、曲艺抄本1600余种，老唱片2万余张，收录了四大名\n旦唯一合唱的老唱片《四五花洞》。\n");
        jScrollPane3.setViewportView(jTextArea3);

        jScrollPane4.setForeground(new java.awt.Color(0, 255, 102));

        jTextArea4.setBackground(new java.awt.Color(0, 153, 51));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("珍贵古籍\n据2018年9月该图书馆官网信息显示，首都图书馆收藏有\n古籍近50万册(件)，其中善本5200余种，67000余册。\n首都图书馆特甄选馆藏珍善本古籍加以数字化，并辅以\n详细书目数据建成\n《馆藏古籍珍善本图像数据库》，数据库所收古籍，均\n为入选《国家珍贵古籍名录》的珍贵古籍和馆藏特色文\n献。148种珍贵古籍入选前五批《国家珍贵古籍名录》\n，包括《阿毗达摩顺正理论》、《毗庐大藏》、《大方\n广佛华严经疏》、《摩诃般若波罗密经》、《古史》60\n卷、《晦庵先生朱文公行状》2卷、《资治通鉴》294卷\n、《通鉴释文辨误》12卷、《通鉴总类》20卷、《唐律\n疏议》30卷、《纂例》12卷等珍贵古籍。 \n");
        jTextArea4.setToolTipText("珍贵古籍\n据2018年9月该图书馆官网信息显示，首都图书馆收藏有古籍近50\n 万册(件)，其中善本5200余种，67000余册。首都图书馆特甄选\n馆藏珍善本古籍加以数字化，并辅以详细书目数据建成《馆藏古\n籍珍善本图像数据库》，数据库所收古籍，均为入选《国家珍贵\n古籍名录》的珍贵古籍和馆藏特色文献。148种珍贵古籍入选前五\n批《国家珍贵古籍名录》，包括《阿毗达摩顺正理论》、《毗庐\n大藏》、《大方广佛华严经疏》、《摩诃般若波罗密经》、《古\n史》60卷、《晦庵先生朱文公行状》2卷、《资治通鉴》294卷、\n《通鉴释文辨误》12卷、《通鉴总类》20卷、《唐律疏议》30卷\n、《纂例》12卷等珍贵古籍。 \n");
        jScrollPane4.setViewportView(jTextArea4);

        jLabel13.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 0));
        jLabel13.setText("GO BACK!");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       New1 l = new New1();
       l.show();
       dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(explanation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(explanation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(explanation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(explanation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new explanation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
